### ISSUE TITLE
data/sensor_graph/adj_mx_unix.pkl

### ISSUE THREAD

**Issue by shirenyu** [xlwang233/pytorch-DCRNN#1]
hi,in the original tensorflow implementation: liyaguang/DCRNN,i can't find "data/sensor_graph/adj_mx_unix.pkl",could you share it ,thx

**Comment by xlwang233** [comment]
You can simply change the "adj_mx_unix.pkl" to "adj_mx.pkl" in the code and use the adj matrix provided by the original author, then it should work just fine.
