### ISSUE TITLE
Can you reproduce the results in the paper?

### ISSUE THREAD

**Issue by LeiBAI** [xlwang233/pytorch-DCRNN#2]
Hello,

thanks for your great work.  Can you successfully reproduce the results reported in the original paper with the pytorch codes??

Thanks 

Lei

**Comment by xlwang233** [comment]
Yes. The test_results.log file contains the results obtained with this code.

Sorry for the late reply cuz I was not at home for the last couple of days.

**Comment by LeiBAI** [comment]
Thanks for your response. the work helps me a lot.
